# Generated by Django 5.2.1 on 2025-06-25 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0003_tarefa_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='data_criacao',
        ),
    ]
